/********************************************************************
* PhosDcsDICT.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PhosDcsDICT.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablePhosDcsDICT();
extern void G__cpp_setup_inheritancePhosDcsDICT();
extern void G__cpp_setup_typetablePhosDcsDICT();
extern void G__cpp_setup_memvarPhosDcsDICT();
extern void G__cpp_setup_globalPhosDcsDICT();
extern void G__cpp_setup_memfuncPhosDcsDICT();
extern void G__cpp_setup_funcPhosDcsDICT();
extern void G__set_cpp_environmentPhosDcsDICT();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PhosConst.h"
#include "PhosDcsBase.h"
#include "PhosDcsBase.cxx"
#include "AltroMenu.h"
#include "ApdInput.h"
#include "ElectronicsMenu.h"
#include "ElectronicsMenuApply.h"
#include "ElectronicsMenuRCU.h"
#include "ElectronicsMenuReadout.h"
#include "ElectronicsMenuGetUserData.h"
#include "FeeCardButton.h"
#include "FeeCardOnOffButton.h"
#include "LogViewer.h"
#include "PhosDcsWidget.h"
#include "PhosHexNumberEntry.h"
#include "PhosMenuButton.h"
#include "PhosNumberEntry.h"
#include "RcuManager.h"
#include "MainGui.h"
#include "MainMenu.h"
#include "RcuButton.h"
#include "SandboxMenu.h"
#include "TruMenu.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PhosDcsDICTLN_tm;
extern G__linked_taginfo G__PhosDcsDICTLN_TClass;
extern G__linked_taginfo G__PhosDcsDICTLN_TBuffer;
extern G__linked_taginfo G__PhosDcsDICTLN_TMemberInspector;
extern G__linked_taginfo G__PhosDcsDICTLN_TObject;
extern G__linked_taginfo G__PhosDcsDICTLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PhosDcsDICTLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PhosDcsDICTLN_TList;
extern G__linked_taginfo G__PhosDcsDICTLN_PhosDcsBase;
extern G__linked_taginfo G__PhosDcsDICTLN_Event_t;
extern G__linked_taginfo G__PhosDcsDICTLN_TGObject;
extern G__linked_taginfo G__PhosDcsDICTLN_TQObject;
extern G__linked_taginfo G__PhosDcsDICTLN_TQObjSender;
extern G__linked_taginfo G__PhosDcsDICTLN_TGWindow;
extern G__linked_taginfo G__PhosDcsDICTLN_TGFrame;
extern G__linked_taginfo G__PhosDcsDICTLN_TGCompositeFrame;
extern G__linked_taginfo G__PhosDcsDICTLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PhosDcsDICTLN_TGTextButton;
extern G__linked_taginfo G__PhosDcsDICTLN_TGMainFrame;
extern G__linked_taginfo G__PhosDcsDICTLN_TGTransientFrame;
extern G__linked_taginfo G__PhosDcsDICTLN_TGGroupFrame;
extern G__linked_taginfo G__PhosDcsDICTLN_TGLabel;
extern G__linked_taginfo G__PhosDcsDICTLN_TGWidget;
extern G__linked_taginfo G__PhosDcsDICTLN_TGButton;
extern G__linked_taginfo G__PhosDcsDICTLN_TGNumberFormat;
extern G__linked_taginfo G__PhosDcsDICTLN_TGNumberFormatcLcLEStyle;
extern G__linked_taginfo G__PhosDcsDICTLN_TGNumberFormatcLcLEAttribute;
extern G__linked_taginfo G__PhosDcsDICTLN_TGNumberFormatcLcLELimit;
extern G__linked_taginfo G__PhosDcsDICTLN_TGNumberEntry;
extern G__linked_taginfo G__PhosDcsDICTLN_PhosNumberEntry;
extern G__linked_taginfo G__PhosDcsDICTLN_TGText;
extern G__linked_taginfo G__PhosDcsDICTLN_TGTextView;
extern G__linked_taginfo G__PhosDcsDICTLN_TGTextEdit;
extern G__linked_taginfo G__PhosDcsDICTLN_PhosDcsWidget;
extern G__linked_taginfo G__PhosDcsDICTLN_ModNumber_t;
extern G__linked_taginfo G__PhosDcsDICTLN_Pattern_t;
extern G__linked_taginfo G__PhosDcsDICTLN_ReadoutConfig_t;
extern G__linked_taginfo G__PhosDcsDICTLN_ConfigInfo_t;
extern G__linked_taginfo G__PhosDcsDICTLN_TRUSettings_t;
extern G__linked_taginfo G__PhosDcsDICTLN_DatabaseDummy;
extern G__linked_taginfo G__PhosDcsDICTLN_PhosMenuButton;
extern G__linked_taginfo G__PhosDcsDICTLN_AltroMenu;
extern G__linked_taginfo G__PhosDcsDICTLN_MainGui;
extern G__linked_taginfo G__PhosDcsDICTLN_ApdInput;
extern G__linked_taginfo G__PhosDcsDICTLN_TGComboBox;
extern G__linked_taginfo G__PhosDcsDICTLN_ElectronicsMenuApply;
extern G__linked_taginfo G__PhosDcsDICTLN_ElectronicsMenuRCU;
extern G__linked_taginfo G__PhosDcsDICTLN_ElectronicsMenuReadout;
extern G__linked_taginfo G__PhosDcsDICTLN_ElectronicsMenu;
extern G__linked_taginfo G__PhosDcsDICTLN_ElectronicsMenuGetUserData;
extern G__linked_taginfo G__PhosDcsDICTLN_FeeCardButton;
extern G__linked_taginfo G__PhosDcsDICTLN_FeeCardOnOffButton;
extern G__linked_taginfo G__PhosDcsDICTLN_LogViewer;
extern G__linked_taginfo G__PhosDcsDICTLN_PhosHexNumberEntry;
extern G__linked_taginfo G__PhosDcsDICTLN_DcsInterface;
extern G__linked_taginfo G__PhosDcsDICTLN_RcuButton;
extern G__linked_taginfo G__PhosDcsDICTLN_RcuManager;
extern G__linked_taginfo G__PhosDcsDICTLN_SandboxMenu;
extern G__linked_taginfo G__PhosDcsDICTLN_TruMenu;
extern G__linked_taginfo G__PhosDcsDICTLN_MainMenu;

/* STUB derived class for protected member access */
